# intoduction to PyTorch

## Tensors
* Data structure that is similarr to arrays and matriced. This is used to encode the inputs and output of a wodel
* It has a similar function to Numpy's ndarrays^, with additional of running it on GPUs 

^ = N dimentional array

Notes on ndarray: 
[[ 1, 2, 3],
      [ 4, 2, 5]]

Here, rank = 2 (as it is 2-dimensional or it has 2 axes)
First dimension(axis) length = 2, second dimension has length = 3
overall shape can be expressed as: (2, 3)

### Tensor's initialization example

In [2]:
import torch
import numpy as np

In [3]:
# directly from the data

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# from a numpy array

np_array = np.array(data)
x_np=torch.from_numpy(np_array)

In [6]:
# from another tensors
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data  with random nombers over the range 0 to 1
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8210, 0.2410],
        [0.4007, 0.4721]]) 



## Shape 
* tuple of tensor dimension

Note: can be referred on tensor's note

In [12]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [13]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}") # torch is the env u should be using for env

Device tensor is stored on: cuda:0


## Standard numpy-like indexing and slicing tensors

In [10]:
# indexing in pytorch
tensor = torch.ones(4, 4)
tensor[2:,1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [20]:
# joining tensors (joining the same index 3 times) 
# dimension 1 = concat horizontaly in 1 dimension (rows)
# dimension 0/-2 = ensuring that number of row is not increasing and concatinate it (columns)

t1 = torch.cat([tensor, tensor, tensor], dim=-1)
print(t1)

# note: this rule is for 2D tensors
# -2 = [:-2] (second last element)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [29]:
# multiplying tensors

print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor} \n")

# ALTERNATIVE EXAMPLE
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

print(f"tensor * tensor \n {tensor_a * tensor_b}")

tensor.mul(tensor) 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[ 5, 12],
        [21, 32]])


In [31]:
# multiplying matrix tensors
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T} \n")

# ALTERNATIVE EXAMPLE
# Define two tensors of the same shape
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# Element-wise multiplication
print(f"tensor a @ tensor b \n {tensor_a @ tensor_b}")
"""[19, 22] = [1*5 + 2*7, 1*6 + 2*8]
[43, 50] = [3*5 + 4*7, 3*6 + 4*8]"""

tensor.matmul(tensor.T) 
 tensor([[4., 4., 3., 3.],
        [4., 4., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[4., 4., 3., 3.],
        [4., 4., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor a @ tensor b 
 tensor([[19, 22],
        [43, 50]])


'[19, 22] = [1*5 + 2*7, 1*6 + 2*8]\n[43, 50] = [3*5 + 4*7, 3*6 + 4*8]'

In [24]:
# the difference look between torch and numpy table

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
